### ISSUE TITLE
Pi Pico initialization issues.

### ISSUE THREAD

**Issue by poetaster** [adafruit/Adafruit_CircuitPython_MAX7219#49] opened 2024-02-12 18:49 UTC
I think it's just a matter of which pins to use. In the micropython context I've been using :  
```
VCC	VBUS (5V)
GND	GND
DIN	GP3 (SPI0_TX)
CS	GP5 (SPI0_CSn)
CLK	GP2 (SPI0_SCK)
```

Which works fine. I tried to adapt this using this driver (installed via circup) and I seem to be missing a pin. On the repl (via screen)

```
>>> import time
>>> import board
>>> import digitalio
>>> from adafruit_max7219 import matrices
>>> 
>>> spi = board.GP3
>>> cs = digitalio.DigitalInOut(board.GP5)
>>>m atrix = matrices.Matrix8x8(spi, cs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_max7219/matrices.py", line 40, in __init__
  File "adafruit_max7219/max7219.py", line 100, in __init__
  File "adafruit_max7219/matrices.py", line 50, in init_display
  File "adafruit_max7219/max7219.py", line 159, in write_cmd
AttributeError: 'Pin' object has no attribute 'try_lock'
```

Hints for the RP2040 would be great. Thanks for all your work!

**Comment by maltize** [comment] 2024-02-23 12:52
I'm using it with Raspberry Pico this way:
```
from adafruit_max7219 import matrices
import busio

spi = busio.SPI(board.GP10, MOSI=board.GP11)
cs = digitalio.DigitalInOut(board.GP13)

matrix = matrices.Matrix8x8(spi, cs)

matrix.fill(True)
matrix.show()
```

**Comment by poetaster** [comment] 2024-02-25 11:31
> I'm using it with Raspberry Pico this way:
> 
> ```
> from adafruit_max7219 import matrices
> import busio
> 
> spi = busio.SPI(board.GP10, MOSI=board.GP11)
> cs = digitalio.DigitalInOut(board.GP13)
> 
> matrix = matrices.Matrix8x8(spi, cs)
> 
> matrix.fill(True)
> matrix.show()
> ```

Thanks! I'll try inititing this way. busio being the difference?

**Comment by FoamyGuy** [comment] 2024-02-26 14:45
@poetaster in the code you posted I think the issue is with this line:
```
spi = board.GP3
```

That is setting the variable `spi` to be a Pin object which it accesses from the `board` module. And then a few lines later `spi` is being passed to the Matrix init function. 

Pretty much all driver init functions that are using the SPI bus are expecting the `spi` argument to be a `busio.SPI` object instance (https://docs.circuitpython.org/en/latest/shared-bindings/busio/index.html#busio.SPI), since yours was actually a Pin object instance it doesn't have the relavent functions and properties that SPI busses have so the driver ends up crashing. 

For devices that have the MOSI, MISO, and SCK pins labeled on the silk screen it's typically possible to use `board.SPI()` note the parenthesis making this a function call unlike `board.GP3` which has no parenthesis. 

Raspberry pi pico boards have very versatile pins that can be used for many purposes and have multiple supported SPI busses that can be exposed on different pins and there aren't any defaults labled on the silk screen so there is no `board.SPI()` on that device, you must use `busio.SPI()` and pass in the pins that you actually hooked up your external device to, such as `busio.SPI(board.GP10, MOSI=board.GP11)` in this case.

**Comment by FoamyGuy** [comment] 2024-03-04 17:44
Closing this for now. Feel free to re-open if you still have this issue after adjusting your code.

**Closed as completed by FoamyGuy** 2024-03-04 17:44 UTC
